"""generate_contracts.py
Generates 18 realistic legal contract PDFs for RegulAIte demo.
Each looks professional and balanced on surface read,
but contains hidden traps the AI agents must catch.

Run: cd regulaite && python contracts/generate_contracts.py
Output: 18 PDF files in regulaite/contracts/
"""

from fpdf import FPDF
import os
import textwrap

OUTPUT_DIR = os.path.join(os.path.dirname(__file__))


class ContractPDF(FPDF):
    def __init__(self, title: str):
        super().__init__()
        self.contract_title = title
        self.set_auto_page_break(auto=True, margin=20)
        self.add_page()
        self.set_margins(25, 20, 25)

    def header(self):
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(120, 120, 120)
        self.cell(0, 8, self.contract_title, align="R", new_x="LMARGIN", new_y="NEXT")
        self.set_text_color(0, 0, 0)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 8, f"Page {self.page_no()}", align="C")
        self.set_text_color(0, 0, 0)

    def add_title(self, text: str):
        self.set_font("Helvetica", "B", 14)
        self.ln(4)
        self.multi_cell(0, 8, text, align="C")
        self.ln(6)

    def add_subtitle(self, text: str):
        self.set_font("Helvetica", "I", 10)
        self.set_text_color(80, 80, 80)
        self.multi_cell(0, 6, text, align="C")
        self.set_text_color(0, 0, 0)
        self.ln(8)

    def add_section(self, number: str, heading: str):
        self.ln(4)
        self.set_font("Helvetica", "B", 11)
        self.multi_cell(0, 7, f"{number}  {heading}")
        self.ln(1)

    def add_clause(self, number: str, text: str):
        self.set_font("Helvetica", "", 10)
        wrapped = f"{number}   {text}"
        self.multi_cell(0, 6, wrapped)
        self.ln(2)

    def add_parties(self, party1: str, party2: str, date: str):
        self.set_font("Helvetica", "", 10)
        self.multi_cell(0, 6,
            f"This Agreement is entered into as of {date} between:\n"
            f"  Party A: {party1} (\"Client\")\n"
            f"  Party B: {party2} (\"Vendor\")\n"
            "collectively referred to as the \"Parties\".")
        self.ln(6)


def save(pdf: ContractPDF, filename: str):
    path = os.path.join(OUTPUT_DIR, filename)
    pdf.output(path)
    print(f"  Created: {filename}")


CONTRACTS = [
    {
        "filename": "01_saas_subscription_agreement.pdf",
        "title": "SOFTWARE-AS-A-SERVICE SUBSCRIPTION AGREEMENT",
        "party1": "Meridian Technologies Pvt. Ltd.",
        "party2": "CloudServe Solutions Inc.",
        "date": "January 15, 2025",
        "sections": [
            ("1", "DEFINITIONS", [
                ("1.1", "\"Service\" means the cloud-based platform provided by Vendor under this Agreement."),
                ("1.2", "\"Data\" means all information uploaded, submitted, or generated by Client through the Service."),
                ("1.3", "\"Confidential Information\" means any non-public information disclosed by either Party."),
            ]),
            ("2", "SUBSCRIPTION AND FEES", [
                ("2.1", "Client shall pay Vendor a monthly subscription fee of INR 2,50,000 payable in advance on the first day of each calendar month."),
                ("2.2", "All fees are non-refundable once the billing cycle has commenced, including in cases of early termination."),
                ("2.3", "Client is entitled to a full refund if services are discontinued by Vendor without cause within the billing period."),
            ]),
            ("3", "TERM AND RENEWAL", [
                ("3.1", "This Agreement commences on the Effective Date and continues for twelve (12) months."),
                ("3.2", "This Agreement shall auto-renew for successive one-year terms unless either Party provides written notice of non-renewal at least 7 days prior to expiry."),
                ("3.3", "No auto-renewal applies to this Agreement; renewal requires mutual written consent from both Parties."),
            ]),
            ("4", "DATA OWNERSHIP AND PRIVACY", [
                ("4.1", "All Client Data remains the exclusive property of the Client at all times."),
                ("4.2", "Vendor may use aggregated, anonymised Client Data for product improvement and may share such data with third-party analytics partners without further consent."),
                ("4.3", "Vendor shall implement appropriate technical measures to protect personal data in accordance with applicable data protection laws."),
            ]),
            ("5", "LIABILITY", [
                ("5.1", "Vendor's total aggregate liability under this Agreement shall not exceed the fees paid by Client in the preceding one (1) month."),
                ("5.2", "Vendor shall bear full and unlimited liability for any damages, losses, or claims arising from service unavailability exceeding 4 hours."),
            ]),
            ("6", "TERMINATION", [
                ("6.1", "Either Party may terminate this Agreement for convenience upon thirty (30) days written notice to the other Party."),
                ("6.2", "Vendor may terminate this Agreement immediately and without notice at its sole discretion for any reason."),
                ("6.3", "Upon termination, Vendor shall return or destroy all Client Data within 7 days."),
            ]),
            ("7", "GOVERNING LAW", [
                ("7.1", "This Agreement shall be governed by the laws of the State of Karnataka, India."),
                ("7.2", "Any disputes shall be resolved exclusively in the courts of Singapore."),
            ]),
        ],
    },
    {
        "filename": "02_vendor_services_agreement.pdf",
        "title": "VENDOR SERVICES AGREEMENT",
        "party1": "Horizon Retail Group",
        "party2": "FastTrack Logistics Pvt. Ltd.",
        "date": "February 3, 2025",
        "sections": [
            ("1", "SCOPE OF SERVICES", [
                ("1.1", "Vendor shall provide last-mile delivery services for all orders placed through Client's platform, including same-day delivery within city limits."),
                ("1.2", "Vendor is not obligated to provide same-day delivery services and may fulfil orders within 3 to 5 business days at its discretion."),
                ("1.3", "Vendor shall maintain a minimum service level of 99.5% on-time delivery rate measured monthly."),
            ]),
            ("2", "PAYMENT TERMS", [
                ("2.1", "Client shall pay Vendor within 15 days of receipt of invoice."),
                ("2.2", "Client shall pay Vendor within 60 days of receipt of invoice, subject to internal approval processes."),
                ("2.3", "Late payments shall attract interest at 24% per annum from the due date."),
                ("2.4", "No interest shall be charged on delayed payments where Client provides prior written notice of delay."),
            ]),
            ("3", "INDEMNIFICATION", [
                ("3.1", "Vendor shall indemnify and hold harmless Client against all third-party claims arising from Vendor's negligence or wilful misconduct."),
                ("3.2", "Client waives all rights to indemnification under this Agreement and agrees to hold Vendor harmless from any and all claims."),
                ("3.3", "Each Party shall maintain adequate insurance coverage for its respective obligations under this Agreement."),
            ]),
            ("4", "CONFIDENTIALITY", [
                ("4.1", "Both Parties agree to keep all business information exchanged under this Agreement strictly confidential for a period of 5 years."),
                ("4.2", "Vendor may freely disclose Client's business information, delivery volumes, and pricing to third parties for benchmarking purposes."),
            ]),
            ("5", "EXCLUSIVITY", [
                ("5.1", "Client grants Vendor exclusive rights to handle all outbound deliveries from Client's warehouses during the term of this Agreement."),
                ("5.2", "This Agreement is non-exclusive and Client may engage any number of alternative logistics providers at any time."),
            ]),
        ],
    },
    {
        "filename": "03_nda_bilateral.pdf",
        "title": "MUTUAL NON-DISCLOSURE AGREEMENT",
        "party1": "Nexus Capital Partners LLP",
        "party2": "BrightPath Analytics Ltd.",
        "date": "March 10, 2025",
        "sections": [
            ("1", "CONFIDENTIAL INFORMATION", [
                ("1.1", "\"Confidential Information\" means all non-public technical, financial, and business information disclosed between the Parties."),
                ("1.2", "Each Party agrees not to disclose Confidential Information to any third party without prior written consent."),
                ("1.3", "Either Party may share Confidential Information with its affiliates, investors, and advisors without restriction or consent from the other Party."),
            ]),
            ("2", "OBLIGATIONS", [
                ("2.1", "Both Parties agree to use Confidential Information solely for the purpose of evaluating a potential business collaboration."),
                ("2.2", "Receiving Party may use Confidential Information for any commercial purpose it deems appropriate, including development of competing products."),
                ("2.3", "Each Party shall use at least the same degree of care to protect the other Party's information as it uses for its own."),
            ]),
            ("3", "TERM", [
                ("3.1", "This Agreement shall remain in effect for two (2) years from the Effective Date."),
                ("3.2", "Confidentiality obligations under this Agreement shall survive indefinitely beyond the termination or expiry of this Agreement."),
                ("3.3", "All confidentiality obligations under this Agreement shall automatically expire upon termination of this Agreement."),
            ]),
            ("4", "REMEDIES", [
                ("4.1", "Each Party acknowledges that breach of this Agreement would cause irreparable harm and agrees that injunctive relief is an appropriate remedy."),
                ("4.2", "The sole remedy for breach of this Agreement shall be monetary damages limited to INR 1,00,000."),
            ]),
        ],
    },
    {
        "filename": "04_employment_contract.pdf",
        "title": "EMPLOYMENT AGREEMENT",
        "party1": "Synapse Digital Solutions Pvt. Ltd.",
        "party2": "Arjun Mehta (Employee)",
        "date": "April 1, 2025",
        "sections": [
            ("1", "POSITION AND DUTIES", [
                ("1.1", "Employee is hired as Senior Product Manager and shall report to the Chief Product Officer."),
                ("1.2", "Employer reserves the right to change Employee's role, reporting line, and responsibilities at any time without Employee's consent."),
                ("1.3", "Employee's duties are as described in Schedule A, which shall not be modified without mutual agreement."),
            ]),
            ("2", "COMPENSATION", [
                ("2.1", "Employee's gross annual compensation shall be INR 28,00,000 payable in equal monthly instalments."),
                ("2.2", "Employer may revise Employee's compensation downward at any time at its sole discretion without prior notice."),
                ("2.3", "Any revision to compensation requires 60 days written notice and Employee's written acceptance."),
            ]),
            ("3", "INTELLECTUAL PROPERTY", [
                ("3.1", "All work product, inventions, and developments created by Employee during employment are the exclusive property of Employer."),
                ("3.2", "Employee retains full ownership of all intellectual property created using personal time and personal equipment."),
                ("3.3", "Employee assigns all intellectual property rights to Employer regardless of when, where, or how it was created."),
            ]),
            ("4", "NON-COMPETE", [
                ("4.1", "Employee agrees not to engage in any competitive activity for a period of 24 months following termination within India."),
                ("4.2", "The non-compete obligation described herein shall not restrict Employee from working in the technology sector."),
                ("4.3", "Employee acknowledges that the non-compete clause is reasonable and agrees to its full enforcement."),
            ]),
            ("5", "TERMINATION", [
                ("5.1", "Either Party may terminate this Agreement with 90 days written notice."),
                ("5.2", "Employer may terminate Employee's employment immediately without notice or compensation for any reason."),
                ("5.3", "Employer shall provide a minimum of 3 months severance pay upon termination without cause."),
                ("5.4", "No severance shall be payable under any circumstances upon termination of employment."),
            ]),
        ],
    },
    {
        "filename": "05_software_license_agreement.pdf",
        "title": "SOFTWARE LICENSE AGREEMENT",
        "party1": "Prakash Manufacturing Ltd.",
        "party2": "TechForge Software LLP",
        "date": "May 5, 2025",
        "sections": [
            ("1", "LICENSE GRANT", [
                ("1.1", "Vendor grants Client a non-exclusive, non-transferable license to use the Software for Client's internal business operations."),
                ("1.2", "Client may sublicense, resell, or redistribute the Software to its subsidiaries and business partners without restriction."),
                ("1.3", "This license is exclusive to Client and Vendor shall not license the same Software to any direct competitor of Client."),
            ]),
            ("2", "PAYMENT", [
                ("2.1", "Client shall pay a one-time license fee of INR 15,00,000 upon execution of this Agreement."),
                ("2.2", "The license fee is fully refundable within 90 days if Client is not satisfied with the Software for any reason."),
                ("2.3", "All license fees are non-refundable and non-transferable under any circumstances."),
            ]),
            ("3", "SUPPORT AND UPDATES", [
                ("3.1", "Vendor shall provide software updates and security patches at no additional cost for the duration of the license."),
                ("3.2", "All updates and new versions of the Software are subject to separate licensing fees and are not included in the base license."),
                ("3.3", "Vendor shall respond to critical support requests within 4 hours on business days."),
            ]),
        ],
    },
    {
        "filename": "06_data_processing_agreement.pdf",
        "title": "DATA PROCESSING AGREEMENT (GDPR COMPLIANT)",
        "party1": "EuroRetail GmbH",
        "party2": "DataVault India Pvt. Ltd.",
        "date": "June 12, 2025",
        "sections": [
            ("1", "SCOPE AND PURPOSE", [
                ("1.1", "Processor shall process Personal Data solely on documented instructions from Controller and for the purposes set forth in Schedule 1."),
                ("1.2", "Processor may process Personal Data for its own internal analytics and product development purposes without additional instruction."),
                ("1.3", "All processing activities shall be limited to the territories listed in Schedule 2."),
            ]),
            ("2", "DATA SUBJECT RIGHTS", [
                ("2.1", "Processor shall assist Controller in responding to Data Subject requests within the timeframes required by applicable law (30 days under GDPR)."),
                ("2.2", "Processor shall have no obligation to facilitate or assist with any Data Subject access, deletion, or portability requests."),
                ("2.3", "Controller retains full responsibility for Data Subject communications and responses."),
            ]),
            ("3", "SECURITY MEASURES", [
                ("3.1", "Processor shall implement appropriate technical and organisational measures to ensure a level of security appropriate to the risk, per GDPR Article 32."),
                ("3.2", "Processor stores all personal data on unencrypted servers and takes no responsibility for data breaches caused by third-party attackers."),
                ("3.3", "Processor shall notify Controller of any personal data breach within 72 hours of becoming aware."),
            ]),
            ("4", "SUB-PROCESSORS", [
                ("4.1", "Processor shall not engage sub-processors without prior specific or general written authorisation from Controller."),
                ("4.2", "Processor may freely engage any sub-processor it deems appropriate without informing Controller."),
            ]),
            ("5", "DATA RETENTION", [
                ("5.1", "Processor shall delete or return all Personal Data upon termination of this Agreement within 30 days."),
                ("5.2", "Processor may retain Personal Data for up to 7 years after termination for its own record-keeping and audit purposes."),
            ]),
        ],
    },
    {
        "filename": "07_freelance_consulting_agreement.pdf",
        "title": "FREELANCE CONSULTING AGREEMENT",
        "party1": "Stellar Brands Pvt. Ltd.",
        "party2": "Riya Sharma (Independent Consultant)",
        "date": "July 7, 2025",
        "sections": [
            ("1", "SERVICES", [
                ("1.1", "Consultant shall provide brand strategy and marketing advisory services as detailed in Statement of Work (SOW) attached hereto."),
                ("1.2", "Client may unilaterally expand the scope of services required without additional compensation to Consultant."),
                ("1.3", "Any changes to the scope of work require mutual written agreement and a revised SOW."),
            ]),
            ("2", "FEES", [
                ("2.1", "Client shall pay Consultant a monthly retainer of INR 1,50,000 payable within 7 days of month end."),
                ("2.2", "Client reserves the right to withhold or defer payment if it determines the deliverables do not meet quality expectations, with no time limit on such deferral."),
                ("2.3", "All disputes regarding payment must be resolved within 30 days or amounts become due automatically."),
            ]),
            ("3", "INTELLECTUAL PROPERTY", [
                ("3.1", "All deliverables created by Consultant under this Agreement shall be considered works made for hire and owned by Client upon full payment."),
                ("3.2", "Consultant retains all moral rights and intellectual property rights in all work created under this Agreement."),
            ]),
        ],
    },
    {
        "filename": "08_lease_agreement_commercial.pdf",
        "title": "COMMERCIAL PROPERTY LEASE AGREEMENT",
        "party1": "Greenleaf Estates LLP (Landlord)",
        "party2": "Nova Ventures Pvt. Ltd. (Tenant)",
        "date": "August 1, 2025",
        "sections": [
            ("1", "TERM", [
                ("1.1", "The lease term shall commence on August 1, 2025 and expire on July 31, 2028, a period of three (3) years."),
                ("1.2", "This lease shall auto-renew for a further three-year term unless Tenant provides notice of non-renewal 180 days in advance."),
                ("1.3", "Tenant may terminate this lease at any time with 30 days notice after the first 12 months."),
            ]),
            ("2", "RENT", [
                ("2.1", "Monthly rent shall be INR 3,50,000 payable on or before the 5th of each month."),
                ("2.2", "Landlord may revise the monthly rent annually by up to 25% without Tenant's consent."),
                ("2.3", "Rent revisions are subject to mutual negotiation and shall not exceed the Consumer Price Index increase."),
            ]),
            ("3", "MAINTENANCE", [
                ("3.1", "Landlord is responsible for structural repairs, external facade, and all common areas."),
                ("3.2", "Tenant is responsible for all repairs, structural or otherwise, arising during the lease term regardless of cause."),
                ("3.3", "Landlord shall complete all notified repair works within 30 days."),
            ]),
        ],
    },
    {
        "filename": "09_partnership_agreement.pdf",
        "title": "BUSINESS PARTNERSHIP AGREEMENT",
        "party1": "Anand Krishnamurthy",
        "party2": "Priya Nambiar",
        "date": "September 15, 2025",
        "sections": [
            ("1", "PROFIT SHARING", [
                ("1.1", "Net profits of the Partnership shall be distributed equally between the Partners at 50% each."),
                ("1.2", "Anand Krishnamurthy shall receive 70% of net profits in recognition of his capital contribution."),
                ("1.3", "Profit distributions shall be made quarterly within 15 days of quarter end."),
            ]),
            ("2", "DECISION MAKING", [
                ("2.1", "All material business decisions require unanimous consent of both Partners."),
                ("2.2", "Anand Krishnamurthy shall have sole and final decision-making authority over all business matters."),
                ("2.3", "Each Partner shall have equal voting rights on all operational matters."),
            ]),
            ("3", "DISSOLUTION", [
                ("3.1", "Either Partner may dissolve the Partnership by providing 6 months written notice to the other."),
                ("3.2", "The Partnership may only be dissolved by mutual written consent of both Partners."),
            ]),
        ],
    },
    {
        "filename": "10_agency_agreement.pdf",
        "title": "COMMERCIAL AGENCY AGREEMENT",
        "party1": "Summit Consumer Goods Ltd.",
        "party2": "Meridian Sales Agency LLP",
        "date": "October 6, 2025",
        "sections": [
            ("1", "APPOINTMENT", [
                ("1.1", "Principal appoints Agent as its exclusive sales representative for the Territory defined in Schedule A."),
                ("1.2", "This appointment is non-exclusive and Principal may appoint other agents or sell directly in the Territory at any time."),
                ("1.3", "Agent shall use its best efforts to promote and sell Principal's products within the Territory."),
            ]),
            ("2", "COMMISSION", [
                ("2.1", "Agent shall earn commission at 8% of net sales invoiced and collected within the Territory."),
                ("2.2", "Principal may vary the commission rate at any time without notice and such variation shall be binding on Agent immediately."),
                ("2.3", "Commission rates may not be revised without 90 days written notice and Agent's written acceptance."),
            ]),
            ("3", "TERMINATION", [
                ("3.1", "This Agreement may be terminated by either Party with 6 months written notice."),
                ("3.2", "Principal may terminate this Agreement immediately without notice, without cause, and without compensation to Agent."),
                ("3.3", "Upon termination, Agent shall be entitled to a goodwill payment equivalent to one year's average commission."),
                ("3.4", "No goodwill, compensation, or severance shall be payable to Agent upon termination under any circumstances."),
            ]),
        ],
    },
    {
        "filename": "11_loan_agreement.pdf",
        "title": "BUSINESS LOAN AGREEMENT",
        "party1": "Bharat Finance Cooperative Ltd. (Lender)",
        "party2": "Starlight Hospitality Pvt. Ltd. (Borrower)",
        "date": "November 1, 2025",
        "sections": [
            ("1", "LOAN AMOUNT AND INTEREST", [
                ("1.1", "Lender shall disburse a loan of INR 2,00,00,000 to Borrower at an annual interest rate of 12% per annum."),
                ("1.2", "Lender reserves the right to revise the interest rate upward at any time without notice, and such revision shall be binding immediately."),
                ("1.3", "The interest rate is fixed for the full term of the loan and shall not be varied."),
            ]),
            ("2", "REPAYMENT", [
                ("2.1", "Borrower shall repay the loan in 36 equal monthly instalments commencing 30 days from disbursement."),
                ("2.2", "Lender may demand full and immediate repayment of the outstanding loan balance at any time without cause."),
                ("2.3", "Borrower shall have the right to prepay the loan without penalty at any time after 12 months."),
                ("2.4", "Prepayment of the loan at any time shall attract a prepayment penalty of 5% of the outstanding principal."),
            ]),
            ("3", "SECURITY", [
                ("3.1", "Borrower shall provide a first mortgage on commercial property situated at Residency Road, Bengaluru, as security."),
                ("3.2", "Lender may invoke security and proceed with sale of the mortgaged property without prior notice to Borrower or court order."),
                ("3.3", "Security may only be enforced through proper legal proceedings with prior notice to Borrower."),
            ]),
        ],
    },
    {
        "filename": "12_reseller_agreement.pdf",
        "title": "PRODUCT RESELLER AGREEMENT",
        "party1": "Alpine Electronics Corp.",
        "party2": "TechDistrib India Pvt. Ltd.",
        "date": "December 3, 2025",
        "sections": [
            ("1", "APPOINTMENT", [
                ("1.1", "Manufacturer appoints Reseller as its authorised exclusive distributor for the Indian market."),
                ("1.2", "Manufacturer may appoint additional distributors or sell directly to end customers in India at any time."),
                ("1.3", "Reseller shall maintain minimum annual purchase volumes of INR 5,00,00,000."),
            ]),
            ("2", "PRICING AND DISCOUNTS", [
                ("2.1", "Reseller shall receive a trade discount of 30% off the published manufacturer price list."),
                ("2.2", "Manufacturer may revise its price list at any time with 7 days notice, which shall automatically revise the discount base."),
                ("2.3", "Reseller's discount shall remain fixed and shall not be reduced without 180 days written notice."),
            ]),
            ("3", "WARRANTY AND RETURNS", [
                ("3.1", "Manufacturer provides a 24-month warranty on all products and shall accept returns of defective units at no cost to Reseller."),
                ("3.2", "Reseller bears full responsibility for all warranty claims and product defects after products leave Manufacturer's warehouse."),
                ("3.3", "Reseller shall not accept product returns from end customers without prior written authorisation from Manufacturer."),
            ]),
        ],
    },
    {
        "filename": "13_marketing_services_agreement.pdf",
        "title": "MARKETING SERVICES AGREEMENT",
        "party1": "BoldBrand Consumer Pvt. Ltd.",
        "party2": "Catalyst Agency LLP",
        "date": "January 20, 2025",
        "sections": [
            ("1", "DELIVERABLES", [
                ("1.1", "Agency shall deliver monthly performance reports, creative assets, and campaign analytics as set out in Schedule B."),
                ("1.2", "Client may at any time change the scope, timelines, and deliverable specifications without additional compensation to Agency."),
                ("1.3", "Deliverable specifications may only be changed through a signed Change Order agreed by both Parties."),
            ]),
            ("2", "INTELLECTUAL PROPERTY", [
                ("2.1", "All creative work product developed by Agency under this Agreement shall be owned by Client upon payment."),
                ("2.2", "Agency retains the right to use all creative work in its portfolio, award submissions, and promotional materials."),
                ("2.3", "Client's brand assets and confidential campaign data shall not be used by Agency in any external communication."),
            ]),
            ("3", "PERFORMANCE AND TERMINATION", [
                ("3.1", "Client may terminate this Agreement for cause with 30 days written notice if Agency fails to meet agreed KPIs."),
                ("3.2", "Client may terminate this Agreement at any time without cause and without notice or compensation."),
                ("3.3", "Upon termination for any reason, Agency shall be entitled to fees for all work completed up to the termination date."),
                ("3.4", "Upon termination, no further amounts shall be payable to Agency regardless of work completed."),
            ]),
        ],
    },
    {
        "filename": "14_subscription_content_agreement.pdf",
        "title": "CONTENT SUBSCRIPTION AND LICENSING AGREEMENT",
        "party1": "MediaStream Networks Ltd.",
        "party2": "ContentHub Creators Pvt. Ltd.",
        "date": "February 28, 2025",
        "sections": [
            ("1", "LICENSE GRANT", [
                ("1.1", "Licensor grants Licensee a worldwide, non-exclusive license to stream and distribute Licensed Content on Licensee's platform."),
                ("1.2", "This license is exclusive to Licensee and Licensor shall not license the same content to any competing streaming platform."),
                ("1.3", "Licensee may sublicense content to third-party platforms with Licensor's prior written consent."),
            ]),
            ("2", "ROYALTIES", [
                ("2.1", "Licensor shall receive royalties equivalent to 20% of net subscription revenue attributable to Licensed Content."),
                ("2.2", "Licensee shall determine revenue attribution at its sole and unreviewable discretion."),
                ("2.3", "Revenue attribution methodology shall be independently audited annually and Licensor shall have audit rights."),
            ]),
            ("3", "CONTENT REMOVAL", [
                ("3.1", "Licensor may request removal of specific content titles with 90 days written notice to Licensee."),
                ("3.2", "Licensee may remove any content at any time without notice and without liability to Licensor."),
                ("3.3", "Removal of content by Licensee without cause entitles Licensor to a proportionate fee reduction."),
                ("3.4", "No fee reduction or credit shall apply in the event of content removal by either Party."),
            ]),
        ],
    },
    {
        "filename": "15_construction_contract.pdf",
        "title": "CONSTRUCTION AND PROJECT MANAGEMENT AGREEMENT",
        "party1": "Radiance Infrastructure Pvt. Ltd. (Owner)",
        "party2": "BuildRight Contractors LLP (Contractor)",
        "date": "March 15, 2025",
        "sections": [
            ("1", "SCOPE OF WORK", [
                ("1.1", "Contractor shall complete construction of a 6-floor commercial building as per approved plans in Schedule C."),
                ("1.2", "Owner may vary the design, materials, and construction scope at any time without additional cost to Owner."),
                ("1.3", "Variations to scope shall be priced and agreed in writing before work commences per a Variation Order."),
            ]),
            ("2", "PAYMENT", [
                ("2.1", "Owner shall pay Contractor in progress payments as certified by the Project Architect per Schedule D."),
                ("2.2", "Owner may withhold any payment at its sole discretion if it determines work quality is unsatisfactory."),
                ("2.3", "Disputed payments shall be resolved within 30 days failing which the undisputed amount becomes due."),
                ("2.4", "Owner's determination on quality and payment amounts shall be final and binding without appeal."),
            ]),
            ("3", "DEFECTS LIABILITY", [
                ("3.1", "Contractor is liable for defects notified within 12 months of project completion (Defects Liability Period)."),
                ("3.2", "Contractor is liable for any structural defect discovered at any time regardless of when construction was completed."),
                ("3.3", "Owner shall provide reasonable access for defect rectification works within the agreed schedule."),
            ]),
            ("4", "INSURANCE", [
                ("4.1", "Contractor shall maintain comprehensive public liability insurance of minimum INR 10,00,00,000."),
                ("4.2", "Owner shall bear all liability for on-site accidents, injuries, and property damage during construction."),
                ("4.3", "Both Parties shall maintain appropriate insurance and neither shall be solely liable for site incidents."),
            ]),
        ],
    },
    {
        "filename": "16_api_integration_agreement.pdf",
        "title": "API ACCESS AND INTEGRATION AGREEMENT",
        "party1": "FinanceOS Platforms Ltd.",
        "party2": "AppBuilder Technologies Pvt. Ltd.",
        "date": "April 14, 2025",
        "sections": [
            ("1", "API ACCESS", [
                ("1.1", "Provider grants Developer non-exclusive access to the FinanceOS API for development and commercial deployment."),
                ("1.2", "Provider may revoke API access at any time without notice and without liability to Developer."),
                ("1.3", "API access shall not be revoked without 90 days notice except in cases of security breach."),
            ]),
            ("2", "DATA USAGE", [
                ("2.1", "Developer may access financial transaction data solely for enabling features within Developer's application."),
                ("2.2", "Provider may access, analyse, and monetise all transaction data flowing through Developer's API integration."),
                ("2.3", "Provider's access to transaction data is limited to security monitoring and service improvement only."),
            ]),
            ("3", "SLA AND UPTIME", [
                ("3.1", "Provider commits to 99.9% API uptime measured monthly, with service credits for shortfalls."),
                ("3.2", "Provider makes no representation or warranty regarding API availability and excludes all liability for downtime."),
                ("3.3", "Service credits shall be Developer's sole remedy for SLA breaches, capped at one month's fees."),
            ]),
        ],
    },
    {
        "filename": "17_healthcare_services_agreement.pdf",
        "title": "HEALTHCARE SERVICES AND DATA AGREEMENT",
        "party1": "WellCare Hospitals Network Ltd.",
        "party2": "MedAnalytics Solutions Pvt. Ltd.",
        "date": "May 19, 2025",
        "sections": [
            ("1", "DATA ACCESS", [
                ("1.1", "Hospital grants Vendor access to de-identified patient records for the purpose of disease pattern analysis."),
                ("1.2", "Vendor may re-identify patient data where technically feasible for improving model accuracy."),
                ("1.3", "All patient data must remain de-identified and Vendor shall implement safeguards to prevent re-identification."),
            ]),
            ("2", "LIABILITY FOR CLINICAL DECISIONS", [
                ("2.1", "Vendor's AI outputs are for decision support only and clinical decisions remain the sole responsibility of treating physicians."),
                ("2.2", "Hospital agrees that Vendor's recommendations constitute medical advice and shall be followed by clinical staff."),
                ("2.3", "Vendor disclaims all liability for clinical outcomes arising from use of its analytical outputs."),
            ]),
            ("3", "REGULATORY COMPLIANCE", [
                ("3.1", "Vendor represents that its software complies with all applicable Indian healthcare data regulations including DPDP Act 2023."),
                ("3.2", "Vendor makes no warranty regarding regulatory compliance and Hospital is solely responsible for ensuring lawful use."),
                ("3.3", "Both Parties shall cooperate with regulatory authorities and notify each other of any regulatory inquiry within 48 hours."),
            ]),
        ],
    },
    {
        "filename": "18_joint_venture_agreement.pdf",
        "title": "JOINT VENTURE AGREEMENT",
        "party1": "Pinnacle Infrastructure Holdings Ltd.",
        "party2": "GreenBuild Developers Pvt. Ltd.",
        "date": "June 30, 2025",
        "sections": [
            ("1", "CONTRIBUTION", [
                ("1.1", "Pinnacle shall contribute INR 10,00,00,000 in cash and GreenBuild shall contribute land and regulatory approvals."),
                ("1.2", "Each Party shall contribute equally in cash, with land valued at market price forming GreenBuild's contribution in kind."),
                ("1.3", "Contributions shall be verified by a mutually appointed independent valuer within 30 days of signing."),
            ]),
            ("2", "GOVERNANCE", [
                ("2.1", "The JV Board shall consist of 2 nominees from each Party and all resolutions require a simple majority."),
                ("2.2", "Pinnacle shall have the right to appoint 3 Board nominees giving it effective majority control."),
                ("2.3", "Reserved matters including land disposal, external financing, and exit require unanimous board approval."),
            ]),
            ("3", "EXIT AND BUYOUT", [
                ("3.1", "Either Party may trigger a buyout by offering to purchase the other Party's interest at fair market value."),
                ("3.2", "GreenBuild may not exit or transfer its interest for a period of 5 years from the Effective Date."),
                ("3.3", "Pinnacle may exit at any time by selling its interest to any third party without GreenBuild's consent."),
                ("3.4", "Neither Party may transfer or sell its interest without the prior written consent of the other Party."),
            ]),
        ],
    },
]


def generate_all():
    print(f"\nGenerating {len(CONTRACTS)} legal contracts into: {OUTPUT_DIR}\n")
    for contract in CONTRACTS:
        pdf = ContractPDF(title=contract["title"])
        pdf.add_title(contract["title"])
        pdf.add_subtitle("CONFIDENTIAL - FOR REVIEW PURPOSES ONLY")
        pdf.add_parties(contract["party1"], contract["party2"], contract["date"])

        for sec_num, sec_heading, clauses in contract["sections"]:
            pdf.add_section(sec_num, sec_heading)
            for clause_num, clause_text in clauses:
                pdf.add_clause(f"{sec_num}.{clause_num.split('.')[-1]}", clause_text)

        pdf.add_section("SIGNATURES", "")
        pdf.add_clause("", f"For and on behalf of {contract['party1']}:")
        pdf.ln(8)
        pdf.add_clause("", "Authorised Signatory: _______________________")
        pdf.add_clause("", "Name & Designation:  _______________________")
        pdf.add_clause("", "Date:                _______________________")
        pdf.ln(8)
        pdf.add_clause("", f"For and on behalf of {contract['party2']}:")
        pdf.ln(8)
        pdf.add_clause("", "Authorised Signatory: _______________________")
        pdf.add_clause("", "Name & Designation:  _______________________")
        pdf.add_clause("", "Date:                _______________________")

        save(pdf, contract["filename"])

    print(f"\nDone. {len(CONTRACTS)} contracts generated.\n")


if __name__ == "__main__":
    generate_all()
